name: Keep Streamlit Alive

on:
  schedule:
    - cron: "0 */9 * * *"   # every 9 hours
  workflow_dispatch:

jobs:
  redeploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create keepalive commit
        run: |
          git commit --allow-empty -m "chore: keepalive [skip ci]" || echo "No changes to commit"
          git push

      - name: Remove keepalive commit
        run: |
          git reset --hard HEAD~1
          git push --force